export type FormrErrorCode =
  | 'FORMR_PATH_EMPTY'
  | 'FORMR_PATH_INVALID_DOT'
  | 'FORMR_PATH_INVALID_POINTER'
  | 'FORMR_PATH_INVALID_POINTER_ESCAPE'
  | 'FORMR_PATH_MIXED_NAMESPACE'
  | 'FORMR_PATH_NOT_DOT_SAFE'
  | 'FORMR_STAGE_UNKNOWN'
  | 'FORMR_EXTENSION_INCOMPATIBLE'
  | 'FORMR_EXTENSION_INVALID_MANIFEST'
  | 'FORMR_EXTENSION_DUPLICATE'
  | 'FORMR_TIMEOUT'
  | 'FORMR_RENDERER_UNKNOWN_TYPE'
  | 'FORMR_PROTOTYPE_POLLUTION'
  | 'FORMR_SUBMIT_CONCURRENT'
  | 'FORMR_ASYNC_IN_SYNC_PIPELINE'
  | 'FORMR_RULE_WRITE_CONFLICT'
  | 'FORMR_RULE_NON_CONVERGENT'
  | 'FORMR_RULE_DISALLOWED_TARGET';

export class FormrError extends Error {
  readonly code: FormrErrorCode;

  constructor(code: FormrErrorCode, message: string) {
    super(message);
    this.name = 'FormrError';
    this.code = code;
  }
}
